language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_7ff58609b516_key -iv $encrypted_7ff58609b516_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
